services:
  web:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - api
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    networks:
      - network-backend
  api:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
    networks:
      - network-backend
  db:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network-backend

networks:
  network-backend:
